### ISSUE TITLE
希望能有一个较为详细的使用说明

### ISSUE THREAD

**Issue by Clusm** [LuckyTime1025/xiaohongshu#2]
@LuckyTime1025非常感谢你的代码，我正在打算基于你的代码进行修改实现一个类似的功能，但是我在配置文件方面遇到一些问题。希望能有一个较为详细的项目介绍。如果可以的话请同时把你的赞赏码或者数字钱包地址提供在md文档末尾。

**Comment by LuckyTime1025** [comment]
我会逐步完善文档的
Clusm ***@***.***> 于 2023年4月26日周三 15:13写道：
