### ISSUE TITLE
添加话题功能

### ISSUE THREAD

**Issue by Y93936543** [LuckyTime1025/xiaohongshu#3]
我模拟点击话题按钮输入话题 在模拟点击检索出来的话题 不成功
我执行js往post-textarea添加固定的html代码 不成功
大佬你有什么好方法吗

**Comment by LuckyTime1025** [comment]
你的代码和报错信息贴一下吧

> 我模拟点击话题按钮输入话题 在模拟点击检索出来的话题 不成功 我执行js往post-textarea添加固定的html代码 不成功 大佬你有什么好方法吗

**Comment by Y93936543** [comment]
主要修改在这个方法：
第一种我想的是先点击一下话题按钮，再输入话题关键字，检索出来后点击话题，但好像都检索不了。
def input_content():
    Config.Browser.find_element(By.CSS_SELECTOR, "button.css-fm44j:nth-child(2)").click()
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys("恋爱")
    try:
        WebDriverWait(Config.Browser, 10, 0.2).until(
            lambda x: x.find_element(By.CSS_SELECTOR, "ul.li:nth-child(1)")).click()
    except TimeoutException:
        print("网页好像加载失败了！请重试！")
    Config.title = input("请输入标题：")
    Config.describe = input("请输入描述：")
    Config.Browser.find_element(By.CSS_SELECTOR, ".c-input_inner").send_keys(Config.title)
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys(Config.describe)

第二种方式是直接给描述框输入#话题，等检索：
def input_content():
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys("#恋爱")
    try:
        WebDriverWait(Config.Browser, 10, 0.2).until(
            lambda x: x.find_element(By.CSS_SELECTOR, "ul.li:nth-child(1)")).click()
    except TimeoutException:
        print("网页好像加载失败了！请重试！")
    Config.title = input("请输入标题：")
    Config.describe = input("请输入描述：")
    Config.Browser.find_element(By.CSS_SELECTOR, ".c-input_inner").send_keys(Config.title)
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys(Config.describe)

第三种是利用innerHTML插入选中话题后的<a>标签和<span>标签，但我这里还在调试，可能字符串有点问题：
def input_content():
    create_a_js = """
    <a data-topic='{"id":"5be7a48879d44e0001c5665b","name":"恋爱","link":"https://www.xiaohongshu.com/page/topics/5be7a488878aa9000162defa?naviHidden=yes","viewNum":16842975178,"type":"official","smart":false}' contenteditable="false">#恋爱<span class="content-hide">#恋爱</span></a>
    """
    str = f'document.getElementById("post-textarea").innerHTML("{create_a_js}");'
    Config.Browser.execute_script(str)

    Config.title = input("请输入标题：")
    Config.describe = input("请输入描述：")
    Config.Browser.find_element(By.CSS_SELECTOR, ".c-input_inner").send_keys(Config.title)
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys(Config.describe)

**Comment by Y93936543** [comment]
已解决
def input_content():
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys("#恋爱")
    time.sleep(3)
    try:
        WebDriverWait(Config.Browser, 10, 0.2).until(
            lambda x: x.find_element(By.CSS_SELECTOR, "ul > li.publish-topic-item:nth-child(1)")).click()
    except TimeoutException:
        print("网页好像加载失败了！请重试！")
    Config.title = input("请输入标题：")
    Config.describe = input("请输入描述：")
    Config.Browser.find_element(By.CSS_SELECTOR, ".c-input_inner").send_keys(Config.title)
    Config.Browser.find_element(By.CSS_SELECTOR, "#post-textarea").send_keys(Config.describe)
